/**
 * VidForge Dashboard - Build & Environment Injection Script
 * Executed during Vercel deployment: reads Vercel environment variables
 * and updates config.js accordingly.
 */
const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'config.js');

// Read existing config.js
let content = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '';

// Resolve environment variables from Vercel
const deployedUrl =
  process.env.VIDFORGE_RENDER_URL ||
  process.env.VITE_API_URL ||
  process.env.DEPLOYED_WEB_URL ||
  'https://vidforge-forensics.onrender.com';

const githubUrl =
  process.env.VIDFORGE_GITHUB_URL ||
  'https://github.com/ashok280705/VIDEO';

console.log('[VidForge Dashboard Build] Injected configuration:');
console.log(' - DEPLOYED_WEB_URL:', deployedUrl);
console.log(' - GITHUB_REPO_URL:', githubUrl);

const newConfig = `/**
 * Generated by build.js during deployment
 */
window.VIDFORGE_CONFIG = {
  DEPLOYED_WEB_URL: "${deployedUrl.replace(/\/+$/, '')}",
  GITHUB_REPO_URL: "${githubUrl}",
  ENDPOINTS: {
    HEALTH: "${process.env.VIDFORGE_HEALTH_URL || ''}",
    API_CASES: "${process.env.VIDFORGE_API_URL || ''}",
    TIMELINE: "${process.env.VIDFORGE_TIMELINE_URL || ''}",
    PLAYER: "${process.env.VIDFORGE_PLAYER_URL || ''}",
    ASSISTANT: "${process.env.VIDFORGE_COPILOT_URL || ''}",
    ANALYSIS: "${process.env.VIDFORGE_ANALYSIS_URL || ''}",
    REPORTS: "${process.env.VIDFORGE_REPORTS_URL || ''}"
  },
  CUSTOM_LINKS: []
};
`;

fs.writeFileSync(configPath, newConfig, 'utf8');
console.log('[VidForge Dashboard Build] Successfully written config.js');
