/**
 * Generated by build.js during deployment
 */
window.VIDFORGE_CONFIG = {
  DEPLOYED_WEB_URL: "https://vidforge-forensics.onrender.com",
  GITHUB_REPO_URL: "https://github.com/ashok280705/VIDEO",
  ENDPOINTS: {
    HEALTH: "",
    API_CASES: "",
    TIMELINE: "",
    PLAYER: "",
    ASSISTANT: "",
    ANALYSIS: "",
    REPORTS: ""
  },
  CUSTOM_LINKS: []
};
